#image: maven:latest
image: mvn-jdk11-ansible:latest
 

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
    

build-stg:
  stage: build

  tags:
    - maven
  script:
    - cd target
    - pwd
    #- scp -r target/akbadm webuser@showstg2.mypchome.com.tw:/home/webuser/_nico/akbadm
    
    
    #- ansible showstg -m ping
    #- mvn $MAVEN_CLI_OPTS clean verify sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
  only:
    - stg
   
#test:
#  stage: test
#  tags:
#    - maven
#  script:
#    - mvn $MAVEN_CLI_OPTS test

#deploy-stg:
#   stage: deploy
#   tags:
#     - maven
#   script:
#     - rsync
#    # - ansible showstg -m ping
#   only:
#     - stg