#image: maven:latest
image: nico19732001/mvn-jdk11-ansible


before_script:
  ##
  ## Assuming you created the SSH_KNOWN_HOSTS variable, uncomment the
  ## following two lines.
  ##
 
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - cat ~/.ssh/known_hosts

 

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
    - ansible-config/
    

build-stg:
  stage: build

  tags:
    - maven
  script:
    
    #- scp -r target/akbadm webuser@showstg2.mypchome.com.tw:/home/webuser/_nico/akbadm
    
    - cp ansible-config/ansible.cfg /etc/ansible/ansible.cfg
    - cp ansible-config/hosts /etc/ansible/hosts
    
    #- cat .ansible.cfg
    #- cat /builds/akb/akbadm/ansible-config/hosts
    #- cd ansible-config
    #- pwd
    #- cd
    #- cat ansible-config/hosts
    #- ansible --version
    - cd ansible-config
    - ansible-playbook playbook.yml -f 10 
    #- mvn $MAVEN_CLI_OPTS clean verify sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
  only:
    - stg
   
#test:
#  stage: test
#  tags:
#    - maven
#  script:
#    - mvn $MAVEN_CLI_OPTS test

#deploy-stg:
#   stage: deploy
#   tags:
#     - maven
#   script:
#     - rsync
#    # - ansible showstg -m ping
#   only:
#     - stg