#image: maven:latest
image: maven:3-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  tags:
    - maven
  script:
    - ls
    - mvn $MAVEN_CLI_OPTS clean verify sonar:sonar \
      -Dsonar.host.url=http://gitrun.mypchome.com.tw:9000 \
      -Dsonar.login=wanyang3 \
      -Dsonar.password=****** \
      -Dsonar.analysis.mode=preview \
      -Dsonar.gitlab.project_id=$CI_PROJECT_ID \
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA \
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME

    #- find /usr/* -type f|grep tools.jar

#test:
#  stage: test
#  tags:
#    - maven
#  script:
#    - mvn $MAVEN_CLI_OPTS test

#deploy:
#  stage: deploy
#  script:
#    - mvn $MAVEN_CLI_OPTS deploy
#  only:
#    - master